# Generated by Django 5.2.5 on 2025-08-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('order', models.PositiveIntegerField(default=0, help_text='排序，数字越大越靠前')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-order', '-uploaded_at'],
            },
        ),
    ]
