# Generated by Django 5.2.5 on 2025-08-12 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='食堂名称')),
                ('location', models.CharField(max_length=100, verbose_name='位置')),
                ('opening_hours', models.CharField(max_length=50, verbose_name='营业时间')),
                ('stall_count', models.PositiveIntegerField(default=0, verbose_name='档口数量')),
                ('image', models.ImageField(blank=True, null=True, upload_to='canteen_images/', verbose_name='食堂图片')),
            ],
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='档口名称')),
                ('cuisine_type', models.CharField(max_length=50, verbose_name='主营菜系')),
                ('is_open', models.BooleanField(default=True, verbose_name='当前营业状态')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stall_images/', verbose_name='档口图片')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stalls', to='unieat_v1.canteen')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('tags', models.CharField(blank=True, max_length=100, verbose_name='标签')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dish_images/', verbose_name='菜品图片')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='unieat_v1.stall')),
            ],
        ),
    ]
