# Generated by Django 5.2.5 on 2025-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0003_canteen_stall_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='floor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
