# Generated by Django 5.2.5 on 2025-08-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0004_stall_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stall',
            name='is_open',
        ),
        migrations.AddField(
            model_name='stall',
            name='close_time_evening',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='close_time_morning',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='manual_open',
            field=models.BooleanField(default=True, help_text='管理员手动控制营业状态'),
        ),
        migrations.AddField(
            model_name='stall',
            name='open_time_evening',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='open_time_morning',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stall',
            name='cuisine_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stall_images/'),
        ),
        migrations.AlterField(
            model_name='stall',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
