# Generated by Django 5.2.5 on 2025-08-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0005_remove_stall_is_open_stall_close_time_evening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='nutrition_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
