# Generated by Django 5.2.5 on 2025-08-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0006_dish_nutrition_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='nutrition_info',
        ),
    ]
