# Generated by Django 5.2.5 on 2025-08-20 13:07

import unieat_v1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=unieat_v1.models.user_avatar_path),
        ),
    ]
