# Generated by Django 5.2.5 on 2025-08-25 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0011_consumptionrecord_consumptionitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermealrecord',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='usermealrecord',
            name='dish',
        ),
        migrations.AddField(
            model_name='usermealrecord',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.CreateModel(
            name='MealDishRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unieat_v1.dish')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='unieat_v1.usermealrecord')),
            ],
        ),
        migrations.CreateModel(
            name='MealExtraRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='unieat_v1.usermealrecord')),
            ],
        ),
    ]
