# Generated by Django 5.2.5 on 2025-09-19 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0012_remove_usermealrecord_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
            },
        ),
        migrations.AddField(
            model_name='usermealrecord',
            name='items_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mealextrarecord',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='unieat_v1.consumptionrecord'),
        ),
        migrations.AddIndex(
            model_name='consumptionrecord',
            index=models.Index(fields=['stall'], name='unieat_v1_c_stall_i_ff710d_idx'),
        ),
    ]
