# Generated by Django 5.2.5 on 2025-09-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0015_feedback_usermealrecord_items_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='type',
            field=models.CharField(choices=[('fixed', '固定价格'), ('custom', '自定义金额')], default='fixed', help_text='档口价格模式：固定价格 / 自定义金额', max_length=20),
        ),
    ]
