# Generated by Django 5.2.5 on 2025-09-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0016_stall_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('normal', '普通菜品'), ('custom', '自选/称重')], default='normal', max_length=20),
        ),
    ]
