# Generated by Django 5.2.6 on 2025-11-04 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models, connection


def safe_delete_tables(apps, schema_editor):
    """安全删除表，如果表不存在则跳过"""
    db_table_prefix = 'unieat_v1_'
    db_name = connection.settings_dict['NAME']
    
    with connection.cursor() as cursor:
        # 检查并删除 MealDishRecord 表
        table_name = db_table_prefix + 'mealdishrecord'
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = %s 
            AND table_name = %s
        """, [db_name, table_name])
        if cursor.fetchone()[0] > 0:
            cursor.execute(f"DROP TABLE IF EXISTS `{table_name}`")
        
        # 检查并删除 UserMealRecord 表
        table_name = db_table_prefix + 'usermealrecord'
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = %s 
            AND table_name = %s
        """, [db_name, table_name])
        if cursor.fetchone()[0] > 0:
            cursor.execute(f"DROP TABLE IF EXISTS `{table_name}`")


def safe_remove_fields(apps, schema_editor):
    """安全移除字段，如果表不存在则跳过"""
    db_table_prefix = 'unieat_v1_'
    db_name = connection.settings_dict['NAME']
    
    with connection.cursor() as cursor:
        # 检查 UserMealRecord 表是否存在
        table_name = db_table_prefix + 'usermealrecord'
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = %s 
            AND table_name = %s
        """, [db_name, table_name])
        
        if cursor.fetchone()[0] > 0:
            # 表存在，检查并移除字段
            for column in ['canteen_id', 'stall_id', 'user_id']:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM information_schema.columns 
                    WHERE table_schema = %s 
                    AND table_name = %s 
                    AND column_name = %s
                """, [db_name, table_name, column])
                if cursor.fetchone()[0] > 0:
                    try:
                        cursor.execute(f"ALTER TABLE `{table_name}` DROP COLUMN `{column}`")
                    except Exception as e:
                        print(f"Warning: Failed to drop column {column}: {e}")


def safe_add_points_field(apps, schema_editor):
    """安全添加积分字段，如果字段已存在则跳过"""
    db_name = connection.settings_dict['NAME']
    table_name = 'unieat_v1_userprofile'
    
    with connection.cursor() as cursor:
        # 检查字段是否已存在
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.columns 
            WHERE table_schema = %s 
            AND table_name = %s 
            AND column_name = 'points'
        """, [db_name, table_name])
        
        if cursor.fetchone()[0] == 0:
            # 字段不存在，添加字段
            cursor.execute("""
                ALTER TABLE `unieat_v1_userprofile` 
                ADD COLUMN `points` INTEGER UNSIGNED NOT NULL DEFAULT 0
            """)
            print("Added 'points' field to UserProfile")
        else:
            print("'points' field already exists, skipping")


def safe_create_checkin_table(apps, schema_editor):
    """安全创建签到记录表，如果表已存在则跳过"""
    db_name = connection.settings_dict['NAME']
    table_name = 'unieat_v1_checkinrecord'
    
    with connection.cursor() as cursor:
        # 检查表是否已存在
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = %s 
            AND table_name = %s
        """, [db_name, table_name])
        
        if cursor.fetchone()[0] > 0:
            print("CheckInRecord table already exists, skipping creation")
        else:
            # 表不存在，使用 Django 的 schema_editor 来创建表
            # 注意：此时需要从 apps 获取模型，但模型可能还没有定义
            # 所以我们直接使用 SQL 创建表
            try:
                cursor.execute(f"""
                    CREATE TABLE `{table_name}` (
                        `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                        `checkin_date` date NOT NULL,
                        `checkin_time` datetime(6) NOT NULL,
                        `consecutive_days` integer UNSIGNED NOT NULL,
                        `points_earned` integer UNSIGNED NOT NULL,
                        `created_at` datetime(6) NOT NULL,
                        `user_id` integer NOT NULL,
                        CONSTRAINT `{table_name}_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`)
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                """)
                cursor.execute(f"""
                    CREATE INDEX `unieat_v1_c_user_id_e338b6_idx` 
                    ON `{table_name}` (`user_id`, `checkin_date`)
                """)
                cursor.execute(f"""
                    ALTER TABLE `{table_name}` 
                    ADD CONSTRAINT `{table_name}_user_id_checkin_date_unique` 
                    UNIQUE (`user_id`, `checkin_date`)
                """)
                print("Created CheckInRecord table")
            except Exception as e:
                print(f"Warning: Failed to create table: {e}")


def safe_add_indexes_and_constraints(apps, schema_editor):
    """安全添加索引和唯一约束，如果已存在则跳过"""
    db_name = connection.settings_dict['NAME']
    table_name = 'unieat_v1_checkinrecord'
    
    with connection.cursor() as cursor:
        # 检查表是否存在
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = %s 
            AND table_name = %s
        """, [db_name, table_name])
        
        if cursor.fetchone()[0] == 0:
            # 表不存在，不需要添加索引
            return
        
        # 检查索引是否存在
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.statistics 
            WHERE table_schema = %s 
            AND table_name = %s 
            AND index_name = 'unieat_v1_c_user_id_e338b6_idx'
        """, [db_name, table_name])
        
        if cursor.fetchone()[0] == 0:
            try:
                cursor.execute(f"""
                    CREATE INDEX `unieat_v1_c_user_id_e338b6_idx` 
                    ON `{table_name}` (`user_id`, `checkin_date`)
                """)
                print("Added index")
            except Exception as e:
                print(f"Warning: Failed to create index: {e}")
        
        # 检查唯一约束是否存在
        constraint_name = f'{table_name}_user_id_checkin_date_unique'
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.table_constraints 
            WHERE table_schema = %s 
            AND table_name = %s 
            AND constraint_name = %s
        """, [db_name, table_name, constraint_name])
        
        if cursor.fetchone()[0] == 0:
            try:
                cursor.execute(f"""
                    ALTER TABLE `{table_name}` 
                    ADD CONSTRAINT `{constraint_name}` 
                    UNIQUE (`user_id`, `checkin_date`)
                """)
                print("Added unique constraint")
            except Exception as e:
                print(f"Warning: Failed to create unique constraint: {e}")


def reverse_safe_delete_tables(apps, schema_editor):
    """反向操作：这里不需要恢复已删除的表"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0017_dish_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 跳过移除字段操作（如果表不存在，这些操作会失败）
        # 使用 RunPython 来安全处理
        migrations.RunPython(
            code=lambda apps, schema_editor: safe_remove_fields(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        # 安全添加积分字段（如果字段不存在）
        migrations.RunPython(
            code=lambda apps, schema_editor: safe_add_points_field(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        # 安全创建签到记录表（如果表不存在）
        migrations.RunPython(
            code=lambda apps, schema_editor: safe_create_checkin_table(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        # 为了保持迁移状态一致，即使表已存在，我们也需要添加模型定义
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # 数据库操作已经在 safe_create_checkin_table 中完成，这里为空
            ],
            state_operations=[
                migrations.CreateModel(
                    name='CheckInRecord',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('checkin_date', models.DateField(default=django.utils.timezone.now, verbose_name='签到日期')),
                        ('checkin_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='签到时间')),
                        ('consecutive_days', models.PositiveIntegerField(default=1, verbose_name='连续签到天数')),
                        ('points_earned', models.PositiveIntegerField(default=0, verbose_name='本次获得积分')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                    ],
                    options={
                        'verbose_name': '签到记录',
                        'verbose_name_plural': '签到记录',
                        'ordering': ['-checkin_date', '-checkin_time'],
                    },
                ),
            ],
        ),
        # 安全删除旧表
        migrations.RunPython(
            code=safe_delete_tables,
            reverse_code=reverse_safe_delete_tables,
        ),
        # 安全添加索引和唯一约束（如果不存在）
        migrations.RunPython(
            code=lambda apps, schema_editor: safe_add_indexes_and_constraints(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        # 为了保持迁移状态一致，也需要添加状态操作
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='checkinrecord',
                    index=models.Index(fields=['user', 'checkin_date'], name='unieat_v1_c_user_id_e338b6_idx'),
                ),
                migrations.AlterUniqueTogether(
                    name='checkinrecord',
                    unique_together={('user', 'checkin_date')},
                ),
            ],
        ),
    ]
