# Generated by Django 5.2.6 on 2025-11-04 17:04

import django.db.models.deletion
import unieat_v1.models
from django.conf import settings
from django.db import migrations, models, connection


def safe_remove_usermealrecord_fields(apps, schema_editor):
    """安全删除 usermealrecord 表的字段，如果表不存在则跳过"""
    db_name = connection.settings_dict['NAME']
    table_name = 'unieat_v1_usermealrecord'

    with connection.cursor() as cursor:
        # 检查表是否存在
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.tables
            WHERE table_schema = %s
            AND table_name = %s
        """, [db_name, table_name])

        if cursor.fetchone()[0] > 0:
            # 表存在，检查字段是否存在并删除
            for field_name in ['canteen_id', 'stall_id', 'user_id']:
                cursor.execute("""
                    SELECT COUNT(*)
                    FROM information_schema.columns
                    WHERE table_schema = %s
                    AND table_name = %s
                    AND column_name = %s
                """, [db_name, table_name, field_name])
                
                if cursor.fetchone()[0] > 0:
                    cursor.execute(f"ALTER TABLE `{table_name}` DROP COLUMN `{field_name}`")
                    print(f"Dropped column {field_name} from {table_name}")
        else:
            print(f"Table {table_name} does not exist, skipping field removal")


def reverse_safe_remove_usermealrecord_fields(apps, schema_editor):
    """反向操作：不执行任何操作（因为表可能不存在）"""
    pass


def safe_add_points_field(apps, schema_editor):
    """安全添加积分字段，如果字段已存在则跳过"""
    db_name = connection.settings_dict['NAME']
    table_name = 'unieat_v1_userprofile'

    with connection.cursor() as cursor:
        # 检查字段是否已存在
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_schema = %s
            AND table_name = %s
            AND column_name = 'points'
        """, [db_name, table_name])

        if cursor.fetchone()[0] == 0:
            # 字段不存在，添加字段
            cursor.execute("""
                ALTER TABLE `unieat_v1_userprofile`
                ADD COLUMN `points` INTEGER UNSIGNED NOT NULL DEFAULT 0
            """)
            print("Added 'points' field to UserProfile")
        else:
            print("'points' field already exists, skipping")


def safe_create_avatar_table(apps, schema_editor):
    """安全创建 Avatar 表，如果表已存在则跳过"""
    db_name = connection.settings_dict['NAME']
    table_name = 'unieat_v1_avatar'

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.tables
            WHERE table_schema = %s
            AND table_name = %s
        """, [db_name, table_name])

        if cursor.fetchone()[0] > 0:
            print(f"Table {table_name} already exists, skipping creation")
        else:
            # 使用 Django 的 schema_editor 创建表
            from django.apps import apps as django_apps
            Avatar = django_apps.get_model('unieat_v1', 'Avatar')
            schema_editor.create_model(Avatar)
            print(f"Created table {table_name}")


def safe_create_recheckincard_table(apps, schema_editor):
    """安全创建 RecheckInCard 表，如果表已存在则跳过"""
    db_name = connection.settings_dict['NAME']
    table_name = 'unieat_v1_recheckincard'

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.tables
            WHERE table_schema = %s
            AND table_name = %s
        """, [db_name, table_name])

        if cursor.fetchone()[0] > 0:
            print(f"Table {table_name} already exists, skipping creation")
        else:
            from django.apps import apps as django_apps
            RecheckInCard = django_apps.get_model('unieat_v1', 'RecheckInCard')
            schema_editor.create_model(RecheckInCard)
            print(f"Created table {table_name}")


def safe_create_other_tables(apps, schema_editor):
    """安全创建其他新表"""
    db_name = connection.settings_dict['NAME']
    tables_to_create = [
        ('unieat_v1_useravatar', 'UserAvatar'),
        ('unieat_v1_userrecheckincard', 'UserRecheckInCard'),
        ('unieat_v1_pointstransaction', 'PointsTransaction'),
    ]

    with connection.cursor() as cursor:
        for table_name, model_name in tables_to_create:
            cursor.execute("""
                SELECT COUNT(*)
                FROM information_schema.tables
                WHERE table_schema = %s
                AND table_name = %s
            """, [db_name, table_name])

            if cursor.fetchone()[0] > 0:
                print(f"Table {table_name} already exists, skipping creation")
            else:
                try:
                    from django.apps import apps as django_apps
                    Model = django_apps.get_model('unieat_v1', model_name)
                    schema_editor.create_model(Model)
                    print(f"Created table {table_name}")
                except Exception as e:
                    # 如果创建表时出错（可能是约束已存在），记录错误但继续
                    print(f"Error creating table {table_name}: {e}")
                    print(f"Table {table_name} may already exist or have conflicting constraints")


def safe_add_indexes(apps, schema_editor):
    """安全添加索引和约束"""
    db_name = connection.settings_dict['NAME']
    
    with connection.cursor() as cursor:
        # 检查表是否存在
        table_name = 'unieat_v1_useravatar'
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.tables
            WHERE table_schema = %s
            AND table_name = %s
        """, [db_name, table_name])
        
        if cursor.fetchone()[0] == 0:
            print(f"Table {table_name} does not exist, skipping indexes and constraints")
            return
        
        # 检查 PointsTransaction 索引
        index_name = 'unieat_v1_p_user_id_94d7bf_idx'
        points_table = 'unieat_v1_pointstransaction'
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.tables
            WHERE table_schema = %s
            AND table_name = %s
        """, [db_name, points_table])
        
        if cursor.fetchone()[0] > 0:
            cursor.execute("""
                SELECT COUNT(*)
                FROM information_schema.statistics
                WHERE table_schema = %s
                AND table_name = %s
                AND index_name = %s
            """, [db_name, points_table, index_name])
            
            if cursor.fetchone()[0] == 0:
                cursor.execute(f"""
                    CREATE INDEX `{index_name}` ON `{points_table}` (`user_id`, `created_at`)
                """)
                print(f"Created index {index_name}")
            else:
                print(f"Index {index_name} already exists, skipping")
        
        # 检查 UserAvatar 索引
        index_name = 'unieat_v1_u_user_id_6a4d20_idx'
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.statistics
            WHERE table_schema = %s
            AND table_name = %s
            AND index_name = %s
        """, [db_name, table_name, index_name])
        
        if cursor.fetchone()[0] == 0:
            cursor.execute(f"""
                CREATE INDEX `{index_name}` ON `{table_name}` (`user_id`, `is_current`)
            """)
            print(f"Created index {index_name}")
        else:
            print(f"Index {index_name} already exists, skipping")
        
        # 检查 UserAvatar 唯一约束
        constraint_name = 'unieat_v1_useravatar_user_id_avatar_id_b84e4575_uniq'
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.table_constraints
            WHERE table_schema = %s
            AND table_name = %s
            AND constraint_name = %s
        """, [db_name, table_name, constraint_name])
        
        if cursor.fetchone()[0] == 0:
            # 检查是否有其他同名的约束（可能是不同命名）
            cursor.execute("""
                SELECT constraint_name
                FROM information_schema.table_constraints
                WHERE table_schema = %s
                AND table_name = %s
                AND constraint_type = 'UNIQUE'
                AND (
                    constraint_name LIKE '%user_id%avatar_id%'
                    OR constraint_name LIKE '%avatar_id%user_id%'
                )
            """, [db_name, table_name])
            
            existing_constraints = cursor.fetchall()
            if existing_constraints:
                print(f"Found existing unique constraint(s): {[c[0] for c in existing_constraints]}")
                # 如果已有类似的唯一约束，就不创建新的
                print(f"Unique constraint already exists (different name), skipping creation of {constraint_name}")
            else:
                try:
                    cursor.execute(f"""
                        ALTER TABLE `{table_name}` 
                        ADD CONSTRAINT `{constraint_name}` UNIQUE (`user_id`, `avatar_id`)
                    """)
                    print(f"Created unique constraint {constraint_name}")
                except Exception as e:
                    print(f"Failed to create constraint {constraint_name}: {e}")
                    print("Constraint may already exist with different name, skipping")
        else:
            print(f"Unique constraint {constraint_name} already exists, skipping")


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0018_remove_usermealrecord_canteen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    safe_create_avatar_table,
                    lambda apps, schema_editor: None
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Avatar',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=50, verbose_name='头像名称')),
                        ('image', models.ImageField(upload_to=unieat_v1.models.avatar_upload_path, verbose_name='头像图片')),
                        ('price', models.PositiveIntegerField(verbose_name='价格（积分）')),
                        ('is_default', models.BooleanField(default=False, verbose_name='是否默认头像（免费）')),
                        ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                    ],
                    options={
                        'verbose_name': '头像商品',
                        'verbose_name_plural': '头像商品',
                        'ordering': ['price', 'id'],
                    },
                ),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    safe_create_recheckincard_table,
                    lambda apps, schema_editor: None
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='RecheckInCard',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(default='续签卡', max_length=50, verbose_name='名称')),
                        ('price', models.PositiveIntegerField(default=5, verbose_name='价格（积分）')),
                        ('description', models.CharField(default='可以补签前一天未签到的记录', max_length=200, verbose_name='描述')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                    ],
                    options={
                        'verbose_name': '续签卡商品',
                        'verbose_name_plural': '续签卡商品',
                    },
                ),
            ]
        ),
        migrations.RunPython(
            safe_remove_usermealrecord_fields,
            reverse_safe_remove_usermealrecord_fields
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    safe_add_points_field,
                    lambda apps, schema_editor: None
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='points',
                    field=models.PositiveIntegerField(default=0, verbose_name='积分'),
                ),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    safe_create_other_tables,
                    lambda apps, schema_editor: None
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='PointsTransaction',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('transaction_type', models.CharField(choices=[('earn', '获得'), ('spend', '消费')], max_length=10, verbose_name='交易类型')),
                        ('points', models.IntegerField(verbose_name='积分数量')),
                        ('description', models.CharField(max_length=200, verbose_name='描述')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                    ],
                    options={
                        'verbose_name': '积分交易记录',
                        'verbose_name_plural': '积分交易记录',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='UserAvatar',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_current', models.BooleanField(default=False, verbose_name='是否当前使用')),
                        ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                        ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_avatars', to='unieat_v1.avatar', verbose_name='头像')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_avatars', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                    ],
                    options={
                        'verbose_name': '用户头像',
                        'verbose_name_plural': '用户头像',
                    },
                ),
                migrations.CreateModel(
                    name='UserRecheckInCard',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('quantity', models.PositiveIntegerField(default=0, verbose_name='数量')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recheckin_card', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                    ],
                    options={
                        'verbose_name': '用户续签卡',
                        'verbose_name_plural': '用户续签卡',
                    },
                ),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    lambda apps, schema_editor: None,  # 不执行任何操作
                    lambda apps, schema_editor: None
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='MealDishRecord',
                ),
                migrations.DeleteModel(
                    name='UserMealRecord',
                ),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    safe_add_indexes,
                    lambda apps, schema_editor: None
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='pointstransaction',
                    index=models.Index(fields=['user', 'created_at'], name='unieat_v1_p_user_id_94d7bf_idx'),
                ),
                migrations.AddIndex(
                    model_name='useravatar',
                    index=models.Index(fields=['user', 'is_current'], name='unieat_v1_u_user_id_6a4d20_idx'),
                ),
                migrations.AlterUniqueTogether(
                    name='useravatar',
                    unique_together={('user', 'avatar')},
                ),
            ]
        ),
    ]
