# Generated by Django 5.2.6 on 2025-11-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0019_avatar_recheckincard_remove_usermealrecord_canteen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='stock',
            field=models.IntegerField(blank=True, help_text='留空表示无限库存', null=True, verbose_name='库存数量'),
        ),
        migrations.AddField(
            model_name='recheckincard',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AddField(
            model_name='recheckincard',
            name='stock',
            field=models.IntegerField(blank=True, help_text='留空表示无限库存', null=True, verbose_name='库存数量'),
        ),
    ]
