# Generated by Django 5.2.6 on 2025-11-06 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unieat_v1', '0020_avatar_is_available_avatar_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenameCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='改名卡', max_length=50, verbose_name='名称')),
                ('price', models.PositiveIntegerField(default=1, verbose_name='价格（积分）')),
                ('description', models.CharField(default='可以修改一次用户昵称', max_length=200, verbose_name='描述')),
                ('stock', models.IntegerField(blank=True, help_text='留空表示无限库存', null=True, verbose_name='库存数量')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '改名卡商品',
                'verbose_name_plural': '改名卡商品',
            },
        ),
        migrations.CreateModel(
            name='UserRenameCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='数量')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rename_card', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户改名卡',
                'verbose_name_plural': '用户改名卡',
            },
        ),
    ]
